services:
  db:
    image: postgres:16
    container_name: wallet_db
    environment:
      POSTGRES_DB: wallet_db
      POSTGRES_USER: wallet_user
      POSTGRES_PASSWORD: wallet_password
    volumes:
      - postgresdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U wallet_user -d wallet_db"]
      interval: 5s
      timeout: 5s
      retries: 5
  app:
    build:
      context: .
    container_name: wallet_app
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "9000:8000"
    command: /wallet/docker/app.sh

volumes:
  postgresdata:
